version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PORT=3000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SUPERVISOR_EMAIL=${SUPERVISOR_EMAIL}
      - SUPERVISOR_PASSWORD=${SUPERVISOR_PASSWORD}
    restart: unless-stopped
